# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'airQualitySensor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'ObjectiveDropboxOfficial'
	pod 'CHCSVParser'
  # Pods for airQualitySensor

  target 'airQualitySensorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'airQualitySensorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
